### ISSUE TITLE
Navigation Support for external &ref

### ISSUE THREAD

**Issue by loms0815** [31oli31/YAML-Navigator#2]
Try to find a solution in VSCode for $ref references in yaml.

In the zip 
[yaml-ref-test.zip](https://github.com/user-attachments/files/18436368/yaml-ref-test.zip)
two sample files are included: 1) interfaces.yaml and 2) role.yaml

Internal $refs in interfaces.yaml are handled correctly (e.g. "#/intern-roles/WMS"). Ctrl+Click jumps to the referenced yaml.

External $refs from interfaces.yaml into file role.yaml (e.g. "roles.yaml#/roles/OMS") are also handled correctly with this nice extension and after pressing Ctrl-Click the file roles.yaml is opened automatically.

But problem seems to be that navigation to referenced yaml (/roles/OMS) in roles.yaml is missing.

**Comment by 31oli31** [comment]
Thank you for providing the details! 
I think the issue is that you dont use the plugin as intended.

I’ve updated your YAML files to ensure the references work properly.
(It might be useful to know that, to read the YAML files, you’ll need to implement a parser in your programming language that resolves imports recursively. You can find an example of such a parser written in PHP in the README.)

```
import:
  - ./roles.yaml
---
intern-roles:
  OMS: &intern_ORMS
    propperty: "intern1"
  WMS: &intern_WMS
    propperty: "intern2"

test:
  references:
  - $ref: *intern_ORMS
  - $ref: *intern_WMS

  - $ref: *external_ORMS
  - $ref: *external_WMS
```

```
roles:
  OMS: &external_ORMS
    propperty: "external1"
  WMS: &external_WMS
    propperty: "external2"

```
